spring:
  application:
    name: ruoyi-flowable
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml

# Springdoc配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# 日志配置
logging:
  level:
    com.ruoyi: DEBUG
    org.springframework: INFO