SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Flowable Database Schema for MySQL

-- ACT_GE_BYTEARRAY
CREATE TABLE IF NOT EXISTS ACT_GE_BYTEARRAY (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    NAME_ VARCHAR(255),
    DEPLOYMENT_ID_ VARCHAR(64),
    BYTES_ LONGBLOB,
    GENERATED_ TINYINT(1) DEFAULT 0,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_GE_PROPERTY
CREATE TABLE IF NOT EXISTS ACT_GE_PROPERTY (
    NAME_ VARCHAR(64) NOT NULL,
    VALUE_ VARCHAR(300),
    REV_ INT DEFAULT 1,
    PRIMARY KEY (NAME_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('schema.version', '7.2.1.0', 1);
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('schema.history', 'create(7.2.1.0)', 1);
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('next.dbid', '1', 1);

-- ACT_RE_DEPLOYMENT
CREATE TABLE IF NOT EXISTS ACT_RE_DEPLOYMENT (
    ID_ VARCHAR(64) NOT NULL,
    NAME_ VARCHAR(255),
    CATEGORY_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    DEPLOY_TIME_ DATETIME,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RE_PROCDEF
CREATE TABLE IF NOT EXISTS ACT_RE_PROCDEF (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    CATEGORY_ VARCHAR(255),
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255) NOT NULL,
    VERSION_ INT NOT NULL,
    DEPLOYMENT_ID_ VARCHAR(64),
    RESOURCE_NAME_ VARCHAR(4000),
    DGRM_RESOURCE_NAME_ VARCHAR(4000),
    DESCRIPTION_ VARCHAR(4000),
    HAS_START_FORM_KEY_ TINYINT(1) DEFAULT 0,
    HAS_GRAPHICAL_NOTATION_ TINYINT(1) DEFAULT 0,
    SUSPENSION_STATE_ INT DEFAULT 1,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    ENGINE_VERSION_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RE_MODEL
CREATE TABLE IF NOT EXISTS ACT_RE_MODEL (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255),
    CATEGORY_ VARCHAR(255),
    CREATE_TIME_ DATETIME,
    LAST_UPDATE_TIME_ DATETIME,
    VERSION_ INT DEFAULT 1,
    META_INFO_ VARCHAR(4000),
    DEPLOYMENT_ID_ VARCHAR(64),
    EDITOR_SOURCE_VALUE_ID_ VARCHAR(64),
    EDITOR_SOURCE_EXTRA_VALUE_ID_ VARCHAR(64),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_EXECUTION
CREATE TABLE IF NOT EXISTS ACT_RU_EXECUTION (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    PROC_INST_ID_ VARCHAR(64),
    BUSINESS_KEY_ VARCHAR(255),
    PARENT_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    SUPER_EXEC_ VARCHAR(64),
    ACT_ID_ VARCHAR(255),
    IS_ACTIVE_ TINYINT(1) DEFAULT 1,
    IS_CONCURRENT_ TINYINT(1) DEFAULT 0,
    IS_SCOPE_ TINYINT(1) DEFAULT 0,
    IS_EVENT_SCOPE_ TINYINT(1) DEFAULT 0,
    SUSPENSION_STATE_ INT DEFAULT 1,
    CACHED_ENT_STATE_ INT,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    NAME_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_TASK
CREATE TABLE IF NOT EXISTS ACT_RU_TASK (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    NAME_ VARCHAR(255),
    PARENT_TASK_ID_ VARCHAR(64),
    DESCRIPTION_ VARCHAR(4000),
    PRIORITY_ INT DEFAULT 50,
    CREATE_TIME_ DATETIME,
    OWNER_ VARCHAR(255),
    ASSIGNEE_ VARCHAR(255),
    DELEGATION_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    TASK_DEF_KEY_ VARCHAR(255),
    DUE_DATE_ DATETIME,
    FOLLOW_UP_DATE_ DATETIME,
    SUSPENSION_STATE_ INT DEFAULT 1,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    FORM_KEY_ VARCHAR(255),
    CLAIM_TIME_ DATETIME,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_IDENTITYLINK
CREATE TABLE IF NOT EXISTS ACT_RU_IDENTITYLINK (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    GROUP_ID_ VARCHAR(255),
    TYPE_ VARCHAR(255),
    USER_ID_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_VARIABLE
CREATE TABLE IF NOT EXISTS ACT_RU_VARIABLE (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    TYPE_ VARCHAR(255) NOT NULL,
    NAME_ VARCHAR(255) NOT NULL,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    BYTEARRAY_ID_ VARCHAR(64),
    DOUBLE_ DOUBLE,
    LONG_ BIGINT,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_JOB
CREATE TABLE IF NOT EXISTS ACT_RU_JOB (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    TYPE_ VARCHAR(255) NOT NULL,
    LOCK_EXP_TIME_ DATETIME,
    LOCK_OWNER_ VARCHAR(255),
    EXCLUSIVE_ TINYINT(1) DEFAULT 0,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    RETRIES_ INT DEFAULT 3,
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ DATETIME,
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_TIMER_JOB
CREATE TABLE IF NOT EXISTS ACT_RU_TIMER_JOB (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    TYPE_ VARCHAR(255) NOT NULL,
    LOCK_EXP_TIME_ DATETIME,
    LOCK_OWNER_ VARCHAR(255),
    EXCLUSIVE_ TINYINT(1) DEFAULT 0,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    RETRIES_ INT DEFAULT 3,
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ DATETIME,
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    JOB_DEF_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_SUSPENDED_JOB
CREATE TABLE IF NOT EXISTS ACT_RU_SUSPENDED_JOB (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    TYPE_ VARCHAR(255) NOT NULL,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    RETRIES_ INT DEFAULT 3,
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ DATETIME,
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    JOB_DEF_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_DEADLETTER_JOB
CREATE TABLE IF NOT EXISTS ACT_RU_DEADLETTER_JOB (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    TYPE_ VARCHAR(255) NOT NULL,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    RETRIES_ INT DEFAULT 0,
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ DATETIME,
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    JOB_DEF_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_EVENT_SUBSCR
CREATE TABLE IF NOT EXISTS ACT_RU_EVENT_SUBSCR (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    EVENT_TYPE_ VARCHAR(255) NOT NULL,
    EVENT_NAME_ VARCHAR(255),
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    ACTIVITY_ID_ VARCHAR(255),
    CONFIGURATION_ VARCHAR(255),
    CREATED_ DATETIME,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_INCIDENT
CREATE TABLE IF NOT EXISTS ACT_RU_INCIDENT (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    INCIDENT_TIMESTAMP_ DATETIME,
    INCIDENT_TYPE_ VARCHAR(255) NOT NULL,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    ACTIVITY_ID_ VARCHAR(255),
    CAUSE_INCIDENT_ID_ VARCHAR(64),
    ROOT_CAUSE_INCIDENT_ID_ VARCHAR(64),
    CONFIGURATION_ VARCHAR(255),
    INCIDENT_MESSAGE_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_HI_PROCINST
CREATE TABLE IF NOT EXISTS ACT_HI_PROCINST (
    ID_ VARCHAR(64) NOT NULL,
    PROC_INST_ID_ VARCHAR(64) NOT NULL,
    BUSINESS_KEY_ VARCHAR(255),
    PROC_DEF_ID_ VARCHAR(64) NOT NULL,
    START_TIME_ DATETIME NOT NULL,
    END_TIME_ DATETIME,
    DURATION_ BIGINT,
    START_USER_ID_ VARCHAR(255),
    START_ACT_ID_ VARCHAR(255),
    END_ACT_ID_ VARCHAR(255),
    SUPER_PROCESS_INSTANCE_ID_ VARCHAR(64),
    DELETE_REASON_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    NAME_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_HI_ACTINST
CREATE TABLE IF NOT EXISTS ACT_HI_ACTINST (
    ID_ VARCHAR(64) NOT NULL,
    PROC_DEF_ID_ VARCHAR(64) NOT NULL,
    PROC_INST_ID_ VARCHAR(64) NOT NULL,
    EXECUTION_ID_ VARCHAR(64) NOT NULL,
    ACT_ID_ VARCHAR(255) NOT NULL,
    TASK_ID_ VARCHAR(64),
    CALL_PROC_INST_ID_ VARCHAR(64),
    ACT_NAME_ VARCHAR(255),
    ACT_TYPE_ VARCHAR(255) NOT NULL,
    ASSIGNEE_ VARCHAR(255),
    START_TIME_ DATETIME NOT NULL,
    END_TIME_ DATETIME,
    DURATION_ BIGINT,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_HI_TASKINST
CREATE TABLE IF NOT EXISTS ACT_HI_TASKINST (
    ID_ VARCHAR(64) NOT NULL,
    PROC_DEF_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64) NOT NULL,
    NAME_ VARCHAR(255),
    PARENT_TASK_ID_ VARCHAR(64),
    DESCRIPTION_ VARCHAR(4000),
    OWNER_ VARCHAR(255),
    ASSIGNEE_ VARCHAR(255),
    START_TIME_ DATETIME NOT NULL,
    CLAIM_TIME_ DATETIME,
    END_TIME_ DATETIME,
    DURATION_ BIGINT,
    DELETE_REASON_ VARCHAR(4000),
    TASK_DEF_KEY_ VARCHAR(255),
    FORM_KEY_ VARCHAR(255),
    PRIORITY_ INT,
    DUE_DATE_ DATETIME,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_HI_DETAIL
CREATE TABLE IF NOT EXISTS ACT_HI_DETAIL (
    ID_ VARCHAR(64) NOT NULL,
    TYPE_ VARCHAR(255) NOT NULL,
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    ACT_INST_ID_ VARCHAR(64),
    NAME_ VARCHAR(255) NOT NULL,
    VAR_TYPE_ VARCHAR(255),
    REV_ INT,
    TIME_ DATETIME NOT NULL,
    BYTEARRAY_ID_ VARCHAR(64),
    DOUBLE_ DOUBLE,
    LONG_ BIGINT,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_HI_COMMENT
CREATE TABLE IF NOT EXISTS ACT_HI_COMMENT (
    ID_ VARCHAR(64) NOT NULL,
    TYPE_ VARCHAR(255),
    TIME_ DATETIME NOT NULL,
    USER_ID_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    ACTION_ VARCHAR(255),
    MESSAGE_ VARCHAR(4000),
    FULL_MSG_ LONGBLOB,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_HI_ATTACHMENT
CREATE TABLE IF NOT EXISTS ACT_HI_ATTACHMENT (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    USER_ID_ VARCHAR(255),
    FILE_NAME_ VARCHAR(255),
    DESCRIPTION_ VARCHAR(4000),
    TYPE_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    URL_ VARCHAR(4000),
    CONTENT_ID_ VARCHAR(64),
    TIME_ DATETIME,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_HI_IDENTITYLINK
CREATE TABLE IF NOT EXISTS ACT_HI_IDENTITYLINK (
    ID_ VARCHAR(64) NOT NULL,
    GROUP_ID_ VARCHAR(255),
    TYPE_ VARCHAR(255),
    USER_ID_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_ID_GROUP
CREATE TABLE IF NOT EXISTS ACT_ID_GROUP (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    NAME_ VARCHAR(255),
    TYPE_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_ID_USER
CREATE TABLE IF NOT EXISTS ACT_ID_USER (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    FIRST_ VARCHAR(255),
    LAST_ VARCHAR(255),
    EMAIL_ VARCHAR(255),
    PWD_ VARCHAR(255),
    PICTURE_ID_ VARCHAR(64),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_ID_MEMBERSHIP
CREATE TABLE IF NOT EXISTS ACT_ID_MEMBERSHIP (
    USER_ID_ VARCHAR(64) NOT NULL,
    GROUP_ID_ VARCHAR(64) NOT NULL,
    PRIMARY KEY (USER_ID_, GROUP_ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_ID_INFO
CREATE TABLE IF NOT EXISTS ACT_ID_INFO (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    USER_ID_ VARCHAR(64),
    TYPE_ VARCHAR(255),
    KEY_ VARCHAR(255),
    VALUE_ VARCHAR(255),
    PASSWORD_ LONGBLOB,
    PARENT_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_PROCDEF_INFO
CREATE TABLE IF NOT EXISTS ACT_PROCDEF_INFO (
    ID_ VARCHAR(64) NOT NULL,
    PROC_DEF_ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    INFO_JSON_ID_ VARCHAR(64),
    DERIVED_FROM_ VARCHAR(64),
    DERIVED_FROM_ROOT_ VARCHAR(64),
    DERIVED_VERSION_ INT,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_FO_DATABASECHANGELOG
CREATE TABLE IF NOT EXISTS ACT_FO_DATABASECHANGELOG (
    ID_ VARCHAR(255) NOT NULL,
    AUTHOR_ VARCHAR(255) NOT NULL,
    FILENAME_ VARCHAR(255) NOT NULL,
    DATEEXECUTED_ DATETIME NOT NULL,
    ORDEREXECUTED_ INT NOT NULL,
    EXECTYPE_ VARCHAR(10) NOT NULL,
    MD5SUM_ VARCHAR(35),
    DESCRIPTION_ VARCHAR(255),
    COMMENTS_ VARCHAR(255),
    TAG_ VARCHAR(255),
    LIQUIBASE_ VARCHAR(20),
    CONTEXTS_ VARCHAR(255),
    LABELS_ VARCHAR(255),
    DEPLOYMENT_ID_ VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_FO_DATABASECHANGELOGLOCK
CREATE TABLE IF NOT EXISTS ACT_FO_DATABASECHANGELOGLOCK (
    ID_ INT NOT NULL,
    LOCKED_ TINYINT(1) NOT NULL,
    LOCKGRANTED_ DATETIME,
    LOCKEDBY_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ACT_FO_DATABASECHANGELOGLOCK (ID_, LOCKED_) VALUES (1, 0);

-- ACT_RU_BATCH
CREATE TABLE IF NOT EXISTS ACT_RU_BATCH (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    TYPE_ VARCHAR(255) NOT NULL,
    TOTAL_JOB_COUNT_ INT NOT NULL,
    JOBS_CREATED_ INT DEFAULT 0,
    JOBS_PROCESSED_ INT DEFAULT 0,
    STATUS_ VARCHAR(255),
    BATCH_JOB_DEF_ID_ VARCHAR(64),
    SEED_JOB_DEF_ID_ VARCHAR(64),
    MONITOR_JOB_DEF_ID_ VARCHAR(64),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    START_TIME_ DATETIME,
    END_TIME_ DATETIME,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_RU_JOB_DEF
CREATE TABLE IF NOT EXISTS ACT_RU_JOB_DEF (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    PROC_DEF_ID_ VARCHAR(64),
    ACT_ID_ VARCHAR(255),
    JOB_TYPE_ VARCHAR(255),
    JOB_CONFIGURATION_ VARCHAR(4000),
    SUSPENSION_STATE_ INT DEFAULT 1,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_HI_BATCH
CREATE TABLE IF NOT EXISTS ACT_HI_BATCH (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    TYPE_ VARCHAR(255) NOT NULL,
    TOTAL_JOB_COUNT_ INT NOT NULL,
    JOBS_PROCESSED_ INT,
    STATUS_ VARCHAR(255),
    START_TIME_ DATETIME,
    END_TIME_ DATETIME,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_DMN_DECISION_TABLE
CREATE TABLE IF NOT EXISTS ACT_DMN_DECISION_TABLE (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255),
    VERSION_ INT,
    CATEGORY_ VARCHAR(255),
    DEPLOYMENT_ID_ VARCHAR(64),
    RESOURCE_NAME_ VARCHAR(4000),
    DGRM_RESOURCE_NAME_ VARCHAR(4000),
    DESCRIPTION_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_DMN_DEPLOYMENT
CREATE TABLE IF NOT EXISTS ACT_DMN_DEPLOYMENT (
    ID_ VARCHAR(64) NOT NULL,
    NAME_ VARCHAR(255),
    CATEGORY_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    DEPLOY_TIME_ DATETIME,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_DMN_HI_DECISION_EXEC
CREATE TABLE IF NOT EXISTS ACT_DMN_HI_DECISION_EXEC (
    ID_ VARCHAR(64) NOT NULL,
    DECISION_DEFINITION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    ACTIVITY_ID_ VARCHAR(255),
    EVALUATION_TIME_ DATETIME,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    OUTPUT_ VARCHAR(4000),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_CMMN_CASE_DEF
CREATE TABLE IF NOT EXISTS ACT_CMMN_CASE_DEF (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255),
    VERSION_ INT,
    CATEGORY_ VARCHAR(255),
    DEPLOYMENT_ID_ VARCHAR(64),
    RESOURCE_NAME_ VARCHAR(4000),
    DGRM_RESOURCE_NAME_ VARCHAR(4000),
    DESCRIPTION_ VARCHAR(4000),
    HAS_GRAPHICAL_NOTATION_ TINYINT(1) DEFAULT 0,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_CMMN_DEPLOYMENT
CREATE TABLE IF NOT EXISTS ACT_CMMN_DEPLOYMENT (
    ID_ VARCHAR(64) NOT NULL,
    NAME_ VARCHAR(255),
    CATEGORY_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    DEPLOY_TIME_ DATETIME,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_CMMN_RU_CASE_INST
CREATE TABLE IF NOT EXISTS ACT_CMMN_RU_CASE_INST (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    CASE_DEF_ID_ VARCHAR(64),
    BUSINESS_KEY_ VARCHAR(255),
    STATE_ VARCHAR(255),
    START_TIME_ DATETIME,
    START_USER_ID_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_CMMN_RU_PLAN_ITEM_INST
CREATE TABLE IF NOT EXISTS ACT_CMMN_RU_PLAN_ITEM_INST (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    CASE_INST_ID_ VARCHAR(64),
    STAGE_INST_ID_ VARCHAR(64),
    PLAN_ITEM_DEFINITION_ID_ VARCHAR(255),
    NAME_ VARCHAR(255),
    STATE_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_CMMN_HI_CASE_INST
CREATE TABLE IF NOT EXISTS ACT_CMMN_HI_CASE_INST (
    ID_ VARCHAR(64) NOT NULL,
    CASE_DEF_ID_ VARCHAR(64),
    BUSINESS_KEY_ VARCHAR(255),
    STATE_ VARCHAR(255),
    START_TIME_ DATETIME,
    END_TIME_ DATETIME,
    START_USER_ID_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_CMMN_HI_PLAN_ITEM_INST
CREATE TABLE IF NOT EXISTS ACT_CMMN_HI_PLAN_ITEM_INST (
    ID_ VARCHAR(64) NOT NULL,
    CASE_INST_ID_ VARCHAR(64),
    PLAN_ITEM_DEFINITION_ID_ VARCHAR(255),
    NAME_ VARCHAR(255),
    STATE_ VARCHAR(255),
    START_TIME_ DATETIME,
    END_TIME_ DATETIME,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_FO_FORM_DEFINITION
CREATE TABLE IF NOT EXISTS ACT_FO_FORM_DEFINITION (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT DEFAULT 1,
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255),
    VERSION_ INT,
    CATEGORY_ VARCHAR(255),
    DEPLOYMENT_ID_ VARCHAR(64),
    RESOURCE_NAME_ VARCHAR(4000),
    DESCRIPTION_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_FO_FORM_DEPLOYMENT
CREATE TABLE IF NOT EXISTS ACT_FO_FORM_DEPLOYMENT (
    ID_ VARCHAR(64) NOT NULL,
    NAME_ VARCHAR(255),
    CATEGORY_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    DEPLOY_TIME_ DATETIME,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ACT_FO_FORM_RESOURCE
CREATE TABLE IF NOT EXISTS ACT_FO_FORM_RESOURCE (
    ID_ VARCHAR(64) NOT NULL,
    FORM_DEFINITION_ID_ VARCHAR(64),
    NAME_ VARCHAR(255),
    BYTES_ LONGBLOB,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
